---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: YWRtaW4=  # base64 for 'admin'
  password: YWRtaW4xMjM=  # base64 for 'admin123'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-banking-deployment
  labels:
    app: retail-banking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: retail-banking
  template:
    metadata:
      labels:
        app: retail-banking
    spec:
      containers:
      - name: retail-banking
        image: iscanprint/retailbankingapp:2.2
        ports:
        - containerPort: 8080
        env:
        - name: GCP_MYSQL_DB_HOST
          value: mysql-service  # Replace with your MySQL service name if different
        - name: GCP_MYSQL_DB_PORT
          value: "3306"
        - name: GCP_MYSQL_DB_UNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: GCP_MYSQL_DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: retail-banking-service
spec:
  type: NodePort  # Change to LoadBalancer if needed
  selector:
    app: retail-banking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  spring.datasource.url: "jdbc:mysql://${GCP_MYSQL_DB_HOST}:${GCP_MYSQL_DB_PORT}/demo?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Kolkata&useSSL=false"
  spring.datasource.username: "${GCP_MYSQL_DB_UNAME}"
  spring.datasource.password: "${GCP_MYSQL_DB_PASSWD}"




 #echo -n 'admin' | base64
  #echo -n 'admin123' | base64
